from collections.abc import Mapping

import pytest

from autoforge.core.git import GitPullRequestRequest
from autoforge.core.secret import SecretReference
from autoforge.infrastructure.git import (
    GitHubApiResponse,
    GitHubPullRequestError,
    GitHubPullRequestProvider,
)
from autoforge.infrastructure.secret import InMemorySecretProvider

_SHA = "a" * 40
_TOKEN = "github-token-never-log"


class ScriptedGitHubApiClient:
    def __init__(self, responses: list[GitHubApiResponse]) -> None:
        self._responses = responses
        self.calls: list[
            tuple[
                str,
                str,
                Mapping[str, str],
                Mapping[str, str] | None,
                Mapping[str, object] | None,
            ]
        ] = []

    async def request(
        self,
        method: str,
        path: str,
        *,
        headers: Mapping[str, str],
        query: Mapping[str, str] | None = None,
        json_body: Mapping[str, object] | None = None,
    ) -> GitHubApiResponse:
        self.calls.append((method, path, headers, query, json_body))
        if not self._responses:
            raise AssertionError("Unexpected GitHub API request")
        return self._responses.pop(0)


def _request(**changes: object) -> GitPullRequestRequest:
    values: dict[str, object] = {
        "repository_url": "https://github.com/example/repository.git",
        "expected_head_sha": _SHA,
        "head_branch": "autoforge/job-1",
        "base_branch": "main",
        "title": "Generate service",
        "body": "Generated by AutoForge",
        "credential": SecretReference("git/github/token"),
    }
    values.update(changes)
    return GitPullRequestRequest(**values)  # type: ignore[arg-type]


def _reference(sha: str = _SHA) -> GitHubApiResponse:
    return GitHubApiResponse(200, {"object": {"sha": sha}})


def _pull_request(sha: str = _SHA) -> dict[str, object]:
    return {
        "number": 42,
        "html_url": "https://github.com/example/repository/pull/42",
        "head": {"ref": "autoforge/job-1", "sha": sha},
        "base": {"ref": "main"},
    }


def _provider(client: ScriptedGitHubApiClient) -> GitHubPullRequestProvider:
    return GitHubPullRequestProvider(
        api_client=client,
        secret_provider=InMemorySecretProvider({"git/github/token": _TOKEN}),
    )


@pytest.mark.anyio
async def test_provider_verifies_head_and_creates_pull_request() -> None:
    client = ScriptedGitHubApiClient(
        [
            _reference(),
            GitHubApiResponse(200, []),
            GitHubApiResponse(201, _pull_request()),
        ]
    )

    result = await _provider(client).create_or_get(_request())

    assert result.created is True
    assert result.pull_request_id == "42"
    assert [call[0] for call in client.calls] == ["GET", "GET", "POST"]
    assert client.calls[0][1].endswith("/heads/autoforge%2Fjob-1")
    assert client.calls[1][3] == {
        "base": "main",
        "head": "example:autoforge/job-1",
        "state": "open",
    }
    assert client.calls[2][4] == {
        "base": "main",
        "body": "Generated by AutoForge",
        "head": "autoforge/job-1",
        "title": "Generate service",
    }
    assert all(
        _TOKEN not in path
        and _TOKEN not in repr(query)
        and _TOKEN not in repr(json_body)
        for _, path, _, query, json_body in client.calls
    )
    assert all(
        headers["Authorization"] == f"Bearer {_TOKEN}"
        for _, _, headers, _, _ in client.calls
    )


@pytest.mark.anyio
async def test_provider_returns_existing_matching_pull_request() -> None:
    client = ScriptedGitHubApiClient(
        [_reference(), GitHubApiResponse(200, [_pull_request()])]
    )

    result = await _provider(client).create_or_get(_request())

    assert result.created is False
    assert len(client.calls) == 2


@pytest.mark.anyio
async def test_provider_rejects_remote_head_sha_mismatch_before_pr_lookup() -> None:
    client = ScriptedGitHubApiClient([_reference("b" * 40)])

    with pytest.raises(GitHubPullRequestError, match="expected commit"):
        await _provider(client).create_or_get(_request())

    assert len(client.calls) == 1


@pytest.mark.anyio
async def test_provider_recovers_concurrent_creation_as_idempotent_success() -> None:
    client = ScriptedGitHubApiClient(
        [
            _reference(),
            GitHubApiResponse(200, []),
            GitHubApiResponse(422, {"message": "already exists"}),
            GitHubApiResponse(200, [_pull_request()]),
        ]
    )

    result = await _provider(client).create_or_get(_request())

    assert result.created is False
    assert len(client.calls) == 4


@pytest.mark.anyio
async def test_provider_rejects_policy_and_malformed_github_responses() -> None:
    policy_client = ScriptedGitHubApiClient([])
    with pytest.raises(ValueError, match="base branch is not allowed"):
        await _provider(policy_client).create_or_get(_request(base_branch="develop"))
    assert policy_client.calls == []

    with pytest.raises(ValueError, match="branch is invalid"):
        await _provider(policy_client).create_or_get(
            _request(head_branch="autoforge/job?unsafe=true")
        )
    assert policy_client.calls == []

    malformed_client = ScriptedGitHubApiClient(
        [
            _reference(),
            GitHubApiResponse(200, []),
            GitHubApiResponse(201, {}),
        ]
    )
    with pytest.raises(GitHubPullRequestError, match="response is invalid"):
        await _provider(malformed_client).create_or_get(_request())
